//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.17 at 03:32:52 PM ICT 
//


package com.galileoindonesia.schema.session;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}AAAArea"/>
 *         &lt;element ref="{}ActiveInd"/>
 *         &lt;element ref="{}AAACity"/>
 *         &lt;element ref="{}AAADept"/>
 *         &lt;element ref="{}SONCity"/>
 *         &lt;element ref="{}SONDept"/>
 *         &lt;element ref="{}AgntID"/>
 *         &lt;element ref="{}ChkDigit"/>
 *         &lt;element ref="{}AgntInitials"/>
 *         &lt;element ref="{}Duty"/>
 *         &lt;element ref="{}AgncyPCC"/>
 *         &lt;element ref="{}DomMode"/>
 *         &lt;element ref="{}IntlMode"/>
 *         &lt;element ref="{}PNRDataInd"/>
 *         &lt;element ref="{}PNRName"/>
 *         &lt;element ref="{}GrpModeActiveInd"/>
 *         &lt;element ref="{}GrpModeDutyCode"/>
 *         &lt;element ref="{}GrpModePCC"/>
 *         &lt;element ref="{}GrpModeDataInd"/>
 *         &lt;element ref="{}GrpModeName"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "aaaArea",
    "activeInd",
    "aaaCity",
    "aaaDept",
    "sonCity",
    "sonDept",
    "agntID",
    "chkDigit",
    "agntInitials",
    "duty",
    "agncyPCC",
    "domMode",
    "intlMode",
    "pnrDataInd",
    "pnrName",
    "grpModeActiveInd",
    "grpModeDutyCode",
    "grpModePCC",
    "grpModeDataInd",
    "grpModeName"
})
@XmlRootElement(name = "AAAAreaInfo")
public class AAAAreaInfo {

    @XmlElement(name = "AAAArea", required = true)
    protected AAAArea aaaArea;
    @XmlElement(name = "ActiveInd", required = true)
    protected ActiveInd activeInd;
    @XmlElement(name = "AAACity", required = true)
    protected AAACity aaaCity;
    @XmlElement(name = "AAADept", required = true)
    protected AAADept aaaDept;
    @XmlElement(name = "SONCity", required = true)
    protected SONCity sonCity;
    @XmlElement(name = "SONDept", required = true)
    protected SONDept sonDept;
    @XmlElement(name = "AgntID", required = true)
    protected AgntID agntID;
    @XmlElement(name = "ChkDigit", required = true)
    protected ChkDigit chkDigit;
    @XmlElement(name = "AgntInitials", required = true)
    protected AgntInitials agntInitials;
    @XmlElement(name = "Duty", required = true)
    protected Duty duty;
    @XmlElement(name = "AgncyPCC", required = true)
    protected AgncyPCC agncyPCC;
    @XmlElement(name = "DomMode", required = true)
    protected DomMode domMode;
    @XmlElement(name = "IntlMode", required = true)
    protected IntlMode intlMode;
    @XmlElement(name = "PNRDataInd", required = true)
    protected PNRDataInd pnrDataInd;
    @XmlElement(name = "PNRName", required = true)
    protected PNRName pnrName;
    @XmlElement(name = "GrpModeActiveInd", required = true)
    protected GrpModeActiveInd grpModeActiveInd;
    @XmlElement(name = "GrpModeDutyCode", required = true)
    protected GrpModeDutyCode grpModeDutyCode;
    @XmlElement(name = "GrpModePCC", required = true)
    protected GrpModePCC grpModePCC;
    @XmlElement(name = "GrpModeDataInd", required = true)
    protected GrpModeDataInd grpModeDataInd;
    @XmlElement(name = "GrpModeName", required = true)
    protected GrpModeName grpModeName;

    /**
     * Gets the value of the aaaArea property.
     * 
     * @return
     *     possible object is
     *     {@link AAAArea }
     *     
     */
    public AAAArea getAAAArea() {
        return aaaArea;
    }

    /**
     * Sets the value of the aaaArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link AAAArea }
     *     
     */
    public void setAAAArea(AAAArea value) {
        this.aaaArea = value;
    }

    /**
     * Gets the value of the activeInd property.
     * 
     * @return
     *     possible object is
     *     {@link ActiveInd }
     *     
     */
    public ActiveInd getActiveInd() {
        return activeInd;
    }

    /**
     * Sets the value of the activeInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActiveInd }
     *     
     */
    public void setActiveInd(ActiveInd value) {
        this.activeInd = value;
    }

    /**
     * Gets the value of the aaaCity property.
     * 
     * @return
     *     possible object is
     *     {@link AAACity }
     *     
     */
    public AAACity getAAACity() {
        return aaaCity;
    }

    /**
     * Sets the value of the aaaCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link AAACity }
     *     
     */
    public void setAAACity(AAACity value) {
        this.aaaCity = value;
    }

    /**
     * Gets the value of the aaaDept property.
     * 
     * @return
     *     possible object is
     *     {@link AAADept }
     *     
     */
    public AAADept getAAADept() {
        return aaaDept;
    }

    /**
     * Sets the value of the aaaDept property.
     * 
     * @param value
     *     allowed object is
     *     {@link AAADept }
     *     
     */
    public void setAAADept(AAADept value) {
        this.aaaDept = value;
    }

    /**
     * Gets the value of the sonCity property.
     * 
     * @return
     *     possible object is
     *     {@link SONCity }
     *     
     */
    public SONCity getSONCity() {
        return sonCity;
    }

    /**
     * Sets the value of the sonCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link SONCity }
     *     
     */
    public void setSONCity(SONCity value) {
        this.sonCity = value;
    }

    /**
     * Gets the value of the sonDept property.
     * 
     * @return
     *     possible object is
     *     {@link SONDept }
     *     
     */
    public SONDept getSONDept() {
        return sonDept;
    }

    /**
     * Sets the value of the sonDept property.
     * 
     * @param value
     *     allowed object is
     *     {@link SONDept }
     *     
     */
    public void setSONDept(SONDept value) {
        this.sonDept = value;
    }

    /**
     * Gets the value of the agntID property.
     * 
     * @return
     *     possible object is
     *     {@link AgntID }
     *     
     */
    public AgntID getAgntID() {
        return agntID;
    }

    /**
     * Sets the value of the agntID property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgntID }
     *     
     */
    public void setAgntID(AgntID value) {
        this.agntID = value;
    }

    /**
     * Gets the value of the chkDigit property.
     * 
     * @return
     *     possible object is
     *     {@link ChkDigit }
     *     
     */
    public ChkDigit getChkDigit() {
        return chkDigit;
    }

    /**
     * Sets the value of the chkDigit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChkDigit }
     *     
     */
    public void setChkDigit(ChkDigit value) {
        this.chkDigit = value;
    }

    /**
     * Gets the value of the agntInitials property.
     * 
     * @return
     *     possible object is
     *     {@link AgntInitials }
     *     
     */
    public AgntInitials getAgntInitials() {
        return agntInitials;
    }

    /**
     * Sets the value of the agntInitials property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgntInitials }
     *     
     */
    public void setAgntInitials(AgntInitials value) {
        this.agntInitials = value;
    }

    /**
     * Gets the value of the duty property.
     * 
     * @return
     *     possible object is
     *     {@link Duty }
     *     
     */
    public Duty getDuty() {
        return duty;
    }

    /**
     * Sets the value of the duty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duty }
     *     
     */
    public void setDuty(Duty value) {
        this.duty = value;
    }

    /**
     * Gets the value of the agncyPCC property.
     * 
     * @return
     *     possible object is
     *     {@link AgncyPCC }
     *     
     */
    public AgncyPCC getAgncyPCC() {
        return agncyPCC;
    }

    /**
     * Sets the value of the agncyPCC property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgncyPCC }
     *     
     */
    public void setAgncyPCC(AgncyPCC value) {
        this.agncyPCC = value;
    }

    /**
     * Gets the value of the domMode property.
     * 
     * @return
     *     possible object is
     *     {@link DomMode }
     *     
     */
    public DomMode getDomMode() {
        return domMode;
    }

    /**
     * Sets the value of the domMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomMode }
     *     
     */
    public void setDomMode(DomMode value) {
        this.domMode = value;
    }

    /**
     * Gets the value of the intlMode property.
     * 
     * @return
     *     possible object is
     *     {@link IntlMode }
     *     
     */
    public IntlMode getIntlMode() {
        return intlMode;
    }

    /**
     * Sets the value of the intlMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntlMode }
     *     
     */
    public void setIntlMode(IntlMode value) {
        this.intlMode = value;
    }

    /**
     * Gets the value of the pnrDataInd property.
     * 
     * @return
     *     possible object is
     *     {@link PNRDataInd }
     *     
     */
    public PNRDataInd getPNRDataInd() {
        return pnrDataInd;
    }

    /**
     * Sets the value of the pnrDataInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link PNRDataInd }
     *     
     */
    public void setPNRDataInd(PNRDataInd value) {
        this.pnrDataInd = value;
    }

    /**
     * Gets the value of the pnrName property.
     * 
     * @return
     *     possible object is
     *     {@link PNRName }
     *     
     */
    public PNRName getPNRName() {
        return pnrName;
    }

    /**
     * Sets the value of the pnrName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PNRName }
     *     
     */
    public void setPNRName(PNRName value) {
        this.pnrName = value;
    }

    /**
     * Gets the value of the grpModeActiveInd property.
     * 
     * @return
     *     possible object is
     *     {@link GrpModeActiveInd }
     *     
     */
    public GrpModeActiveInd getGrpModeActiveInd() {
        return grpModeActiveInd;
    }

    /**
     * Sets the value of the grpModeActiveInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrpModeActiveInd }
     *     
     */
    public void setGrpModeActiveInd(GrpModeActiveInd value) {
        this.grpModeActiveInd = value;
    }

    /**
     * Gets the value of the grpModeDutyCode property.
     * 
     * @return
     *     possible object is
     *     {@link GrpModeDutyCode }
     *     
     */
    public GrpModeDutyCode getGrpModeDutyCode() {
        return grpModeDutyCode;
    }

    /**
     * Sets the value of the grpModeDutyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrpModeDutyCode }
     *     
     */
    public void setGrpModeDutyCode(GrpModeDutyCode value) {
        this.grpModeDutyCode = value;
    }

    /**
     * Gets the value of the grpModePCC property.
     * 
     * @return
     *     possible object is
     *     {@link GrpModePCC }
     *     
     */
    public GrpModePCC getGrpModePCC() {
        return grpModePCC;
    }

    /**
     * Sets the value of the grpModePCC property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrpModePCC }
     *     
     */
    public void setGrpModePCC(GrpModePCC value) {
        this.grpModePCC = value;
    }

    /**
     * Gets the value of the grpModeDataInd property.
     * 
     * @return
     *     possible object is
     *     {@link GrpModeDataInd }
     *     
     */
    public GrpModeDataInd getGrpModeDataInd() {
        return grpModeDataInd;
    }

    /**
     * Sets the value of the grpModeDataInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrpModeDataInd }
     *     
     */
    public void setGrpModeDataInd(GrpModeDataInd value) {
        this.grpModeDataInd = value;
    }

    /**
     * Gets the value of the grpModeName property.
     * 
     * @return
     *     possible object is
     *     {@link GrpModeName }
     *     
     */
    public GrpModeName getGrpModeName() {
        return grpModeName;
    }

    /**
     * Sets the value of the grpModeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrpModeName }
     *     
     */
    public void setGrpModeName(GrpModeName value) {
        this.grpModeName = value;
    }

}
