//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.17 at 03:32:52 PM ICT 
//


package com.galileoindonesia.schema.session;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Sys"/>
 *         &lt;element ref="{}Processor"/>
 *         &lt;element ref="{}GrpModeActivatedInd"/>
 *         &lt;element ref="{}AAAAreaAry"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sys",
    "processor",
    "grpModeActivatedInd",
    "aaaAreaAry"
})
@XmlRootElement(name = "AreaInfoResp")
public class AreaInfoResp {

    @XmlElement(name = "Sys", required = true)
    protected Sys sys;
    @XmlElement(name = "Processor", required = true)
    protected Processor processor;
    @XmlElement(name = "GrpModeActivatedInd", required = true)
    protected GrpModeActivatedInd grpModeActivatedInd;
    @XmlElement(name = "AAAAreaAry", required = true)
    protected AAAAreaAry aaaAreaAry;

    /**
     * Gets the value of the sys property.
     * 
     * @return
     *     possible object is
     *     {@link Sys }
     *     
     */
    public Sys getSys() {
        return sys;
    }

    /**
     * Sets the value of the sys property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sys }
     *     
     */
    public void setSys(Sys value) {
        this.sys = value;
    }

    /**
     * Gets the value of the processor property.
     * 
     * @return
     *     possible object is
     *     {@link Processor }
     *     
     */
    public Processor getProcessor() {
        return processor;
    }

    /**
     * Sets the value of the processor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Processor }
     *     
     */
    public void setProcessor(Processor value) {
        this.processor = value;
    }

    /**
     * Gets the value of the grpModeActivatedInd property.
     * 
     * @return
     *     possible object is
     *     {@link GrpModeActivatedInd }
     *     
     */
    public GrpModeActivatedInd getGrpModeActivatedInd() {
        return grpModeActivatedInd;
    }

    /**
     * Sets the value of the grpModeActivatedInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrpModeActivatedInd }
     *     
     */
    public void setGrpModeActivatedInd(GrpModeActivatedInd value) {
        this.grpModeActivatedInd = value;
    }

    /**
     * Gets the value of the aaaAreaAry property.
     * 
     * @return
     *     possible object is
     *     {@link AAAAreaAry }
     *     
     */
    public AAAAreaAry getAAAAreaAry() {
        return aaaAreaAry;
    }

    /**
     * Sets the value of the aaaAreaAry property.
     * 
     * @param value
     *     allowed object is
     *     {@link AAAAreaAry }
     *     
     */
    public void setAAAAreaAry(AAAAreaAry value) {
        this.aaaAreaAry = value;
    }

}
