//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.17 at 03:32:52 PM ICT 
//


package com.galileoindonesia.schema.session;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.galileoindonesia.schema.session package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NewPwd_QNAME = new QName("", "NewPwd");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.galileoindonesia.schema.session
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AgntID }
     * 
     */
    public AgntID createAgntID() {
        return new AgntID();
    }

    /**
     * Create an instance of {@link SONCity }
     * 
     */
    public SONCity createSONCity() {
        return new SONCity();
    }

    /**
     * Create an instance of {@link SignOff }
     * 
     */
    public SignOff createSignOff() {
        return new SignOff();
    }

    /**
     * Create an instance of {@link GrpModeDataInd }
     * 
     */
    public GrpModeDataInd createGrpModeDataInd() {
        return new GrpModeDataInd();
    }

    /**
     * Create an instance of {@link Pwd }
     * 
     */
    public Pwd createPwd() {
        return new Pwd();
    }

    /**
     * Create an instance of {@link DomMode }
     * 
     */
    public DomMode createDomMode() {
        return new DomMode();
    }

    /**
     * Create an instance of {@link SessionChangePassword10 }
     * 
     */
    public SessionChangePassword10 createSessionChangePassword10() {
        return new SessionChangePassword10();
    }

    /**
     * Create an instance of {@link ChangePassword }
     * 
     */
    public ChangePassword createChangePassword() {
        return new ChangePassword();
    }

    /**
     * Create an instance of {@link Num }
     * 
     */
    public Num createNum() {
        return new Num();
    }

    /**
     * Create an instance of {@link SessionInfo }
     * 
     */
    public SessionInfo createSessionInfo() {
        return new SessionInfo();
    }

    /**
     * Create an instance of {@link GrpModePCC }
     * 
     */
    public GrpModePCC createGrpModePCC() {
        return new GrpModePCC();
    }

    /**
     * Create an instance of {@link AAAArea }
     * 
     */
    public AAAArea createAAAArea() {
        return new AAAArea();
    }

    /**
     * Create an instance of {@link GrpModeActivatedInd }
     * 
     */
    public GrpModeActivatedInd createGrpModeActivatedInd() {
        return new GrpModeActivatedInd();
    }

    /**
     * Create an instance of {@link SONDept }
     * 
     */
    public SONDept createSONDept() {
        return new SONDept();
    }

    /**
     * Create an instance of {@link AAADept }
     * 
     */
    public AAADept createAAADept() {
        return new AAADept();
    }

    /**
     * Create an instance of {@link Sys }
     * 
     */
    public Sys createSys() {
        return new Sys();
    }

    /**
     * Create an instance of {@link AreaInfoResp }
     * 
     */
    public AreaInfoResp createAreaInfoResp() {
        return new AreaInfoResp();
    }

    /**
     * Create an instance of {@link GrpModeActiveInd }
     * 
     */
    public GrpModeActiveInd createGrpModeActiveInd() {
        return new GrpModeActiveInd();
    }

    /**
     * Create an instance of {@link NewArea }
     * 
     */
    public NewArea createNewArea() {
        return new NewArea();
    }

    /**
     * Create an instance of {@link AAAAreaInfo }
     * 
     */
    public AAAAreaInfo createAAAAreaInfo() {
        return new AAAAreaInfo();
    }

    /**
     * Create an instance of {@link UserID }
     * 
     */
    public UserID createUserID() {
        return new UserID();
    }

    /**
     * Create an instance of {@link AreaInfoReq }
     * 
     */
    public AreaInfoReq createAreaInfoReq() {
        return new AreaInfoReq();
    }

    /**
     * Create an instance of {@link ChkDigit }
     * 
     */
    public ChkDigit createChkDigit() {
        return new ChkDigit();
    }

    /**
     * Create an instance of {@link SignOn }
     * 
     */
    public SignOn createSignOn() {
        return new SignOn();
    }

    /**
     * Create an instance of {@link SecurityMessage }
     * 
     */
    public SecurityMessage createSecurityMessage() {
        return new SecurityMessage();
    }

    /**
     * Create an instance of {@link AgntInitials }
     * 
     */
    public AgntInitials createAgntInitials() {
        return new AgntInitials();
    }

    /**
     * Create an instance of {@link IntlMode }
     * 
     */
    public IntlMode createIntlMode() {
        return new IntlMode();
    }

    /**
     * Create an instance of {@link PNRDataInd }
     * 
     */
    public PNRDataInd createPNRDataInd() {
        return new PNRDataInd();
    }

    /**
     * Create an instance of {@link NewKeyword }
     * 
     */
    public NewKeyword createNewKeyword() {
        return new NewKeyword();
    }

    /**
     * Create an instance of {@link AAAAreaAry }
     * 
     */
    public AAAAreaAry createAAAAreaAry() {
        return new AAAAreaAry();
    }

    /**
     * Create an instance of {@link ChangeWorkArea }
     * 
     */
    public ChangeWorkArea createChangeWorkArea() {
        return new ChangeWorkArea();
    }

    /**
     * Create an instance of {@link GrpModeDutyCode }
     * 
     */
    public GrpModeDutyCode createGrpModeDutyCode() {
        return new GrpModeDutyCode();
    }

    /**
     * Create an instance of {@link GrpModeName }
     * 
     */
    public GrpModeName createGrpModeName() {
        return new GrpModeName();
    }

    /**
     * Create an instance of {@link AgncyPCC }
     * 
     */
    public AgncyPCC createAgncyPCC() {
        return new AgncyPCC();
    }

    /**
     * Create an instance of {@link ActiveInd }
     * 
     */
    public ActiveInd createActiveInd() {
        return new ActiveInd();
    }

    /**
     * Create an instance of {@link Duty }
     * 
     */
    public Duty createDuty() {
        return new Duty();
    }

    /**
     * Create an instance of {@link PCC }
     * 
     */
    public PCC createPCC() {
        return new PCC();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link TextLen }
     * 
     */
    public TextLen createTextLen() {
        return new TextLen();
    }

    /**
     * Create an instance of {@link Processor }
     * 
     */
    public Processor createProcessor() {
        return new Processor();
    }

    /**
     * Create an instance of {@link EmulatePCC }
     * 
     */
    public EmulatePCC createEmulatePCC() {
        return new EmulatePCC();
    }

    /**
     * Create an instance of {@link SessionMods }
     * 
     */
    public SessionMods createSessionMods() {
        return new SessionMods();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link AAACity }
     * 
     */
    public AAACity createAAACity() {
        return new AAACity();
    }

    /**
     * Create an instance of {@link PNRName }
     * 
     */
    public PNRName createPNRName() {
        return new PNRName();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NewPwd")
    public JAXBElement<String> createNewPwd(String value) {
        return new JAXBElement<String>(_NewPwd_QNAME, String.class, null, value);
    }

}
